# Check that the code works
name: Check dialogue code

# Check this on the 16th day of the month.
# 16th as the first letter of this repo is the 16th letter in the alphabet.
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"


jobs:
  check-dialogue-code:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        run: |
            install.packages("remotes")
            remotes::install_cran("testthat")
            remotes::install_cran("readr")
            remotes::install_cran("stringr")
            remotes::install_cran("ggplot2")
            remotes::install_cran("dplyr")
            remotes::install_cran("svglite")
        shell: Rscript {0}

      - name: Run
        run: ./scripts/create_pdf_of_rmd_dialogue.R
