# Check that there is correct spelling in all files
name: Check spelling

# Check this on the 16th day of the month.
# 16th as the first letter of this repo is the 16th letter in the alphabet.
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"


jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Ignore rendered document
        run: rm docs/dialogue/dialogue.md

      - uses: igsekor/pyspelling-any@v1.0.4



